### ISSUE TITLE
Changing velocity boundary conditions

### ISSUE THREAD

**Issue by sb926** [LukeMondy/lithospheric_modelling_recipe#10]
Hi Luke,
I'm running into some errors trying to implement depth dependent velocity for BCs. I've been trying to keep the input as simple as possible, so started with using a structure based on the example that you give on the wiki (https://bitbucket.org/lmondy/lithosphericmodellingrecipe/wiki/lmrVelocityBoundaries.xml). 

The error message is:
2: Component dictionary must have unique names
2: Error found in given dictionary:
2: The following keys were repeated:
2:  "elevation"
2: Error in CheckDictionaryKeys with 1 entries in dictionary keys

I'm a bit confused about why it throws this error because elevation is only given once as a structure name and the other time it is given as a field name. Is it set somewhere else as well?

I've attached VB input file.

[lmrVelocityBoundaries.txt](https://github.com/OlympusMonds/lithospheric_modelling_recipe/files/139884/lmrVelocityBoundaries.txt)

**Comment by OlympusMonds** [comment]
Hi Sarah,

Yeah, I predicted this may happen - it's because in lmrOtherProcesses.xml, the surface processes stuff already defines "elevation". You can either just use that, or rename your one to some other name.

Sorry about that!

**Comment by sb926** [comment]
Ah, OK! Thanks for working it out so quickly! :) I think I'll try to use a different name in the velocity boundaries and keep experimenting.

Cheers!

**Comment by sb926** [comment]
I changed the name of structure to 'velocityDepth' and it seems to be working now.
I just wanted to ask also about the structuring of the lmrVelocityBoundaries.xml input file when adding a function as velocity BC rather than simply defined walls like the default. 

When I add the function is it necessary to keep these lines for it to work? :
structure name velocityBCs 
param name CompositeVC
list name vcList

And is it fine to keep the bottom wall defined with the lecode_tools_Isostasy? 

I tried a few different arrangements of where I put the function and what I included in the structure but most didn't work so thought it might be worth being clear on what's essential to keep if others are going to try to change this!

**Comment by OlympusMonds** [comment]
Yes, you do need the 
```
structure name velocityBCs 
param name CompositeVC
list name vcList
```
stuff.

All good to keep isostasy.

The function you define needs to be in the components struct, not in the velocityBCs struct.
Underneath all the WallVC definitions, you can see this:
```
    <struct name="components" mergeType="merge">
        <struct name="current_time" mergeType="replace">
            <param name="Type"> Ppc_Current_Time </param>
        </struct>
        
        <struct name="left-wall-VC">
            <param name="Type"> Ppc_Switch </param>
            <param name="Field"> current_time </param>
            <param name="Interpolate"> l </param>
            <list name="CaseList">
                <struct>
                    <param name="Case" units="Myr"> 0 </param>
                    <param name="Value" units="cm/yr"> -0.2 </param>
                </struct>
                <struct>
                    <param name="Case" units="Myr"> 1 </param>
                    <param name="Value" units="cm/yr"> -2.0 </param>
                </struct>
            </list>
        </struct>
        
    </struct>
```
(To be technical about it, the components place is where you can instantiate new objects. We need some functions, so we gotta put them in the components struct.)

So yeah, once you have defined your function in there, you can then replace something like this:
```
            <struct>
                <param name="type"> WallVC </param>
                <param name="wall"> front </param>
                <list name="variables">
                    <struct>
                        <param name="name"> vz </param>
                        <param name="type"> double </param>
                        <param name="value" units="cm/yr"> 0.0 </param>
                    </struct>
                </list>
            </struct>
```
with something like this:
```
            <struct>
                <param name="type"> WallVC </param>
                <param name="wall"> front </param>
                <list name="variables">
                    <struct>
                        <param name="name"> vz </param>
                        <param name="type"> func</param>
                        <param name="value"> a_function_defined_in_the_components_struct </param>
                    </struct>
                </list>
            </struct>
```

**Comment by sb926** [comment]
Thanks very much for clarifying all of that! It's really helpful.
