### ISSUE TITLE
Trouble defining simple polygon - Signal 11 'SIGSEGV' (Segmentation Fault)

### ISSUE THREAD

**Issue by lmahoney9** [LukeMondy/lithospheric_modelling_recipe#6]
Hi Luke,

I'm having trouble defining a very simple polygon shape for the Upper Crust (lmrMaterials attached).

When running thermal equilibration I receive the following error: 

Initialising Stg_Components from the live-component register

Laying out material 'air' within Box 'airShape':
Laying out material 'sediment' within Box 'SedShape':
# 

Error running Underworld - Signal 11 
# 

Error running Underworld - Signal 11 'SIGSEGV' (Segmentation Fault).
This is probably caused by an illegal access of memory.
We recommend running the code in a debugger to work out where the problem is (e.g. 'gdb')
and also to contact the developers.
'SIGSEGV' (Segmentation Fault).
This is probably caused by an illegal access of memory.
We recommend running the code in a debugger to work out where the problem is (e.g. 'gdb')
and also to contact the developers.

The equilibration runs fine when the polygon shape is replaced by a simple box.

Any ideas?

Thanks again,
Luke

[lmrMaterials.txt](https://github.com/OlympusMonds/lithospheric_modelling_recipe/files/83523/lmrMaterials.txt)

**Comment by OlympusMonds** [comment]
Hey Luke, I'll give this a crack tomorrow.

**Comment by OlympusMonds** [comment]
Oops, sorry, bit late!
In the lmrMaterials.txt you sent, there is no sedshape that is a polygon - can you send that one through?

**Comment by lmahoney9** [comment]
Hi Luke, The sedshape is a rectangle and upper crust a polygon (which should overprint)?

**Comment by OlympusMonds** [comment]
Right, sorry! Looking into it now.
